import = ["/home/tomm/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window.padding]
x = 5
y = 5

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono Nerd Font"

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "Never"
shape = "Beam"
